// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class P21_ai_search_jobsProjection
{
    public const string Resource = "ai-search-jobs";
    public const string OperationIds = "ai-search-namespace-instance-change-job-status;ai-search-namespace-instance-create-job;ai-search-namespace-instance-get-job;ai-search-namespace-instance-list-jobs";
    public const string CmdletNames = "Get-CfAiSearchJob;New-CfAiSearchJob;Set-CfAiSearchJob";
    public const string ScopeBindings = "account_id:Account:Parent;id:Instance:Nested;job_id:Job:Primary;name:Namespace:Nested";
}