// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class P21_zonesProjection
{
    public const string Resource = "zones";
    public const string OperationIds = "zones-0-delete;zones-0-get;zones-0-patch;zones-get;zones-post";
    public const string CmdletNames = "Get-CfZone;New-CfZone;Remove-CfZone;Set-CfZone";
    public const string ScopeBindings = "zone_id:Zone:Primary";
}