<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cloudflare.PowerShell</RootNamespace>
    <AssemblyName>Cloudflare.PowerShell</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Generated/Experiments/**/*.cs" />
  </ItemGroup>
</Project>
