<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cloudflare.PowerShell</RootNamespace>
    <AssemblyName>Cloudflare.PowerShell</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Generated/Experiments/**/*.cs" />
    <PackageReference Include="System.Management.Automation"
                      Version="7.6.0"
                      PrivateAssets="all"
                      ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
