<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cloudflare.PowerShell</RootNamespace>
    <AssemblyName>Cloudflare.PowerShell</AssemblyName>
    <PowerShellHome Condition="'$(PowerShellHome)' == ''">$(ProgramFiles)\PowerShell\7</PowerShellHome>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Generated/Experiments/**/*.cs" />
    <Reference Include="System.Management.Automation">
      <HintPath>$(PowerShellHome)\System.Management.Automation.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
