[CmdletBinding()]
param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $ProjectRoot 'tools/ReadOnlyStaging.ps1') -Library
. (Join-Path $ProjectRoot 'tools/P33ReadOnlyStaging.ps1') -Library
$declared=@(Get-P33D2RequiredInputPaths -ProjectRoot $ProjectRoot)
foreach($required in @('Cloudflare.P1.sln','artifacts/p3.2/CmdletModel.json','artifacts/p3.3/coverage-baseline.json','overrides/powershell-p33-d2-healthchecks-projection.json','tools/Generate-P33D2HealthchecksFixture.ps1','tools/Project-P33D2Projection.ps1','tools/Generate-P33D2Source.ps1','tests/P33D1Smoke.ps1','tests/P33D2Smoke.ps1')){if($declared-notcontains$required){throw "D2 staging declaration omitted required input: $required"}}
foreach($forbidden in @('fixtures/p3.3/d1-database/document.json','fixtures/p3.3/healthchecks/document.json','artifacts/p3.3/CmdletModel.json','artifacts/p3.3/healthchecks/CmdletModel.json','artifacts/p3.3/healthchecks/d2-projection-compatibility.json','src/Cloudflare.PowerShell/Generated/Cmdlets/P33D2HealthchecksCmdlets.cs','src/Cloudflare.PowerShell/Generated/Metadata/CfHealthCheckRuntimeMetadata.cs')){if($declared-contains$forbidden){throw "D2 staging declaration unexpectedly stages generated output: $forbidden"}}
$root=Join-Path ([IO.Path]::GetTempPath()) ('p33-d2-staging-contract-'+[guid]::NewGuid().ToString('N'))
try{$input=Join-Path $root 'input';$stage=Join-Path $root 'stage';New-Item -ItemType Directory -Force -Path (Join-Path $input '.git/objects/pack'),(Join-Path $input 'bin'),(Join-Path $input 'cache')|Out-Null;'required'|Set-Content (Join-Path $input 'required.cs') -Encoding utf8NoBOM;'pack'|Set-Content (Join-Path $input '.git/objects/pack/fake') -Encoding utf8NoBOM;'build'|Set-Content (Join-Path $input 'bin/out') -Encoding utf8NoBOM;'cache'|Set-Content (Join-Path $input 'cache/e') -Encoding utf8NoBOM;'other'|Set-Content (Join-Path $input 'other.cs') -Encoding utf8NoBOM;Copy-ReadOnlyStagingFiles -SourceRoot $input -DestinationRoot $stage -RelativePaths @('required.cs');$inventory=@(Assert-ReadOnlyStagingInputContract -Root $stage -ExpectedRelativePaths @('required.cs'));if($inventory.Count-ne 1){throw 'D2 required staging input was not copied.'};foreach($bad in @('.git','bin','cache','other.cs')){if(Test-Path -LiteralPath (Join-Path $stage $bad)){throw "D2 staging admitted forbidden input: $bad"}};$failed=$false;try{Copy-ReadOnlyStagingFiles -SourceRoot $input -DestinationRoot (Join-Path $root 'missing') -RelativePaths @('missing.json')}catch{$failed=$true};if(-not$failed){throw 'D2 staging did not fail for a missing input.'};Write-Output 'PASS P3.3 D2 exact-set staging declaration and missing/VCS/build/cache negative contract'}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
