<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cloudflare.Normalization</RootNamespace>
    <AssemblyName>Cloudflare.Normalization</AssemblyName>
  </PropertyGroup>
</Project>
