// <auto-generated />
namespace Cloudflare.PowerShell;

public static class CfDnsRecordOperations
{
    public const string CreateOperationId = "dns-records-for-a-zone-create-dns-record";
    public const string DeleteOperationId = "dns-records-for-a-zone-delete-dns-record";
    public const string EditOperationId = "dns-records-for-a-zone-patch-dns-record";
    public const string GetOperationId = "dns-records-for-a-zone-dns-record-details";
    public const string ListOperationId = "dns-records-for-a-zone-list-dns-records";
    public const string UpdateOperationId = "dns-records-for-a-zone-update-dns-record";
}
