// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class GetCfDnsRecord
{
    public const string OperationId = "dns-records-for-a-zone-dns-record-details;dns-records-for-a-zone-list-dns-records";
    public const string HttpMethod = "GET;GET";
    public const string PathTemplate = "/zones/{zone_id}/dns_records/{dns_record_id}";
    public const string OutputType = "Cloudflare.PowerShell.CfDnsRecord";
    public const string ParameterSet = "Replace,Edit";
    public const bool SupportsShouldProcess = false;
}
