// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class NewCfDnsRecord
{
    public const string OperationId = "dns-records-for-a-zone-create-dns-record";
    public const string HttpMethod = "POST";
    public const string PathTemplate = "/zones/{zone_id}/dns_records";
    public const string OutputType = "Cloudflare.PowerShell.CfDnsRecord";
    public const string ParameterSet = "";
    public const bool SupportsShouldProcess = true;
}
