// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class Projection_Get_CfDnsRecord
{
    public const string CmdletName = "Get-CfDnsRecord";
    public const string OperationIds = "dns-records-for-a-zone-dns-record-details;dns-records-for-a-zone-list-dns-records";
    public const string HttpMethods = "GET;GET";
    public const string OutputType = "Cloudflare.PowerShell.CfDnsRecord";
    public const string ConfirmImpact = "None";
    public const bool SupportsShouldProcess = false;
}