// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class Projection_Remove_CfDnsRecord
{
    public const string CmdletName = "Remove-CfDnsRecord";
    public const string OperationIds = "dns-records-for-a-zone-delete-dns-record";
    public const string HttpMethods = "DELETE";
    public const string OutputType = "Cloudflare.PowerShell.CfDnsRecord";
    public const string ConfirmImpact = "High";
    public const bool SupportsShouldProcess = true;
}