// <auto-generated />
#nullable enable
namespace Cloudflare.PowerShell;

public static class SetCfDnsRecord
{
    public const string OperationId = "dns-records-for-a-zone-patch-dns-record;dns-records-for-a-zone-update-dns-record";
    public const string HttpMethod = "PATCH;PUT";
    public const string PathTemplate = "/zones/{zone_id}/dns_records/{dns_record_id}";
    public const string OutputType = "Cloudflare.PowerShell.CfDnsRecord";
    public const string ParameterSet = "Replace,Edit";
    public const bool SupportsShouldProcess = true;
}
